// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddLocationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }
  [Test]
  public void addLocation() {
    // Test name: AddLocation
    // Step # | name | target | value
    // 1 | open | https://localhost:44300/Account/Login?ReturnUrl=%2FLocation | 
    driver.Navigate().GoToUrl("https://localhost:44300/Account/Login?ReturnUrl=%2FLocation");
    // 2 | setWindowSize | 1552x849 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 849);
    // 3 | click | css=label:nth-child(3) | 
    driver.FindElement(By.CssSelector("label:nth-child(3)")).Click();
    // 4 | click | css=.btn-default | 
    driver.FindElement(By.CssSelector(".btn-default")).Click();
    // 5 | click | css=tr:nth-child(2) | 
    driver.FindElement(By.CssSelector("tr:nth-child(2)")).Click();
    // 6 | click | linkText=Create New | 
    vars["WindowHandles"] = driver.WindowHandles;
    // 7 | storeWindowHandle | root | 
    driver.FindElement(By.LinkText("Create New")).Click();
    // 8 | selectWindow | handle=${win4593} | 
    vars["win4593"] = waitForWindow(2000);
    // 9 | click | id=Name | 
    vars["root"] = driver.CurrentWindowHandle;
    // 10 | type | id=Name | Palaza 1
    driver.SwitchTo().Window(vars["win4593"].ToString());
    // 11 | type | id=TotalVacancies | 5
    driver.FindElement(By.Id("Name")).Click();
    // 12 | selectWindow | handle=${root} | 
    driver.FindElement(By.Id("Name")).SendKeys("Palaza 1");
    // 13 | selectWindow | handle=${win4593} | 
    driver.FindElement(By.Id("TotalVacancies")).SendKeys("5");
    // 14 | type | id=Lat | 72.17379751868164	
    driver.SwitchTo().Window(vars["root"].ToString());
    // 15 | selectWindow | handle=${root} | 
    driver.SwitchTo().Window(vars["win4593"].ToString());
    // 16 | click | css=td:nth-child(4) | 
    driver.FindElement(By.Id("Lat")).SendKeys("72.17379751868164	");
    // 17 | selectWindow | handle=${win4593} | 
    driver.SwitchTo().Window(vars["root"].ToString());
    // 18 | click | id=Long | 
    driver.FindElement(By.CssSelector("td:nth-child(4)")).Click();
    // 19 | type | id=Long | 29.80303923076786
    driver.SwitchTo().Window(vars["win4593"].ToString());
    // 20 | click | id=Address | 
    driver.FindElement(By.Id("Long")).Click();
    // 21 | type | id=Address | Mailsi
    driver.FindElement(By.Id("Long")).SendKeys("29.80303923076786");
    // 22 | click | id=Price | 
    driver.FindElement(By.Id("Address")).Click();
    // 23 | type | id=Price | 20
    driver.FindElement(By.Id("Address")).SendKeys("Mailsi");
    // 24 | type | id=Price | 15
    driver.FindElement(By.Id("Price")).Click();
    // 25 | click | id=IsActive | 
    driver.FindElement(By.Id("Price")).SendKeys("20");
    // 26 | click | css=.btn-default | 
    driver.FindElement(By.Id("Price")).SendKeys("15");
    driver.FindElement(By.Id("IsActive")).Click();
    driver.FindElement(By.CssSelector(".btn-default")).Click();
  }
}
