// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new FirefoxOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void login() {
    // Test name: Login
    // Step # | name | target | value
    // 1 | open | https://localhost:44300/Account/Login | 
    driver.Navigate().GoToUrl("https://localhost:44300/Account/Login");
    // 2 | setWindowSize | 1148x692 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1148, 692);
    // 3 | click | id=RememberMe | 
    driver.FindElement(By.Id("RememberMe")).Click();
    // 4 | click | css=.btn-default | 
    driver.FindElement(By.CssSelector(".btn-default")).Click();
    // 5 | runScript | window.scrollTo(0,211.1999969482422) | 
    js.ExecuteScript("window.scrollTo(0,211.1999969482422)");
    // 6 | click | linkText=Log off | 
    driver.FindElement(By.LinkText("Log off")).Click();
    // 7 | mouseOver | id=registerLink | 
    {
      var element = driver.FindElement(By.Id("registerLink"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 8 | close |  | 
    driver.Close();
    // 9 | click | id=Email | 
    driver.FindElement(By.Id("Email")).Click();
    // 10 | type | id=Email | us
    driver.FindElement(By.Id("Email")).SendKeys("us");
    // 11 | sendKeys | id=Email | ${KEY_DOWN}
    driver.FindElement(By.Id("Email")).SendKeys(Keys.Down);
    // 12 | sendKeys | id=Email | ${KEY_TAB}
    driver.FindElement(By.Id("Email")).SendKeys(Keys.Tab);
    // 13 | click | css=label:nth-child(3) | 
    driver.FindElement(By.CssSelector("label:nth-child(3)")).Click();
    // 14 | click | css=.btn-default | 
    driver.FindElement(By.CssSelector(".btn-default")).Click();
    // 15 | mouseOver | linkText=About | 
    {
      var element = driver.FindElement(By.LinkText("About"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
