// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegistrationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new FirefoxOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registration() {
    // Test name: Registration
    // Step # | name | target | value
    // 1 | open | https://localhost:44300/Account/Register | 
    driver.Navigate().GoToUrl("https://localhost:44300/Account/Register");
    // 2 | setWindowSize | 1552x849 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 849);
    // 3 | click | css=.form-group:nth-child(6) > .col-md-2 | 
    driver.FindElement(By.CssSelector(".form-group:nth-child(6) > .col-md-2")).Click();
    // 4 | click | id=Email | 
    driver.FindElement(By.Id("Email")).Click();
    // 5 | type | id=Email | usama.anwar@gmail.com
    driver.FindElement(By.Id("Email")).SendKeys("usama.anwar@gmail.com");
    // 6 | click | id=Password | 
    driver.FindElement(By.Id("Password")).Click();
    // 7 | type | id=Password | Mzainnoor910@
    driver.FindElement(By.Id("Password")).SendKeys("Mzainnoor910@");
    // 8 | type | id=ConfirmPassword | Mzainnoor91@
    driver.FindElement(By.Id("ConfirmPassword")).SendKeys("Mzainnoor91@");
    // 9 | click | css=.btn-default | 
    driver.FindElement(By.CssSelector(".btn-default")).Click();
    // 10 | click | css=.text-danger li | 
    driver.FindElement(By.CssSelector(".text-danger li")).Click();
    // 11 | click | css=.text-danger li | 
    driver.FindElement(By.CssSelector(".text-danger li")).Click();
    // 12 | click | id=Password | 
    driver.FindElement(By.Id("Password")).Click();
    // 13 | type | id=ConfirmPassword | Mzainnoor910@
    driver.FindElement(By.Id("ConfirmPassword")).SendKeys("Mzainnoor910@");
    // 14 | sendKeys | id=ConfirmPassword | ${KEY_ENTER}
    driver.FindElement(By.Id("ConfirmPassword")).SendKeys(Keys.Enter);
  }
}
