// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ReservationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new FirefoxOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void reservation() {
    // Test name: Reservation
    // Step # | name | target | value
    // 1 | open | https://localhost:44300/ | 
    driver.Navigate().GoToUrl("https://localhost:44300/");
    // 2 | setWindowSize | 1148x692 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1148, 692);
    // 3 | mouseOver | linkText=My Parkings | 
    {
      var element = driver.FindElement(By.LinkText("My Parkings"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 4 | click | css=.gm-style > div:nth-child(2) > div:nth-child(2) | 
    driver.FindElement(By.CssSelector(".gm-style > div:nth-child(2) > div:nth-child(2)")).Click();
    // 5 | click | css=div:nth-child(3) > div > img | 
    driver.FindElement(By.CssSelector("div:nth-child(3) > div > img")).Click();
    // 6 | click | id=reserve | 
    driver.FindElement(By.Id("reserve")).Click();
  }
}
